apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-server
  namespace: development
spec:
  serviceName: "db-service"
  replicas: 2
  selector:
    matchLabels:
      app: db-server
  template:
    metadata:
      labels:
        app: db-server
    spec:
      containers:
      - name: db-container
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db-username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db-password
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: root-password
        resources:
          requests:
            cpu: "250m"  # 0.25 CPU
            memory: "512Mi"
          limits:
            cpu: "500m"  # 0.5 CPU
            memory: "1Gi"
        volumeMounts:
        - name: db-storage
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: db-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
