apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: development
type: Opaque
stringData:
  db-username: db-user     
  db-password: db-Passw0rd     
  root-password: r00t-Passw0rd     
